<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>crl</string>
		<string>th</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>CRL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.crl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.crl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!(CRL_VERSION|DEFINE|TARGET|TYPE|URL|AUTH_URL|CHECKOUT|REPO_PATH|REPO_BRANCH|NAME|ANON_USER|ANON_PASS)</string>
			<key>name</key>
			<string>keyword.operator.directive.crl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$\w+</string>
			<key>name</key>
			<string>variable.other.match.crl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.crl</string>
	<key>uuid</key>
	<string>E4466265-8CB6-44D5-BF65-89445E30CC6E</string>
</dict>
</plist>
